# Generated by Django 4.1.13 on 2025-09-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade_type',
            field=models.CharField(choices=[('regular', 'Thường xuyên'), ('midterm', 'Giữa kỳ'), ('final', 'Cuối kỳ'), ('assignment', 'Bài tập'), ('quiz', 'Kiểm tra'), ('other', 'Khác')], max_length=20),
        ),
    ]
