# Generated by Django 4.1.13 on 2025-09-26 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_alter_grade_grade_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='component',
            field=models.CharField(blank=True, choices=[('lecture', 'Lý thuyết'), ('practice', 'Thực hành')], max_length=20, null=True),
        ),
    ]
