# Generated by Django 4.2.7 on 2025-09-30 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0003_grade_component'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['subject_id'], 'verbose_name': 'Môn học (Grades)', 'verbose_name_plural': 'Môn học (Grades)'},
        ),
        migrations.AlterModelTable(
            name='subject',
            table='grades_subjects',
        ),
    ]
