# Generated by Django 4.1.13 on 2025-10-01 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_academicyear_subject_term_and_more'),
        ('grades', '0004_alter_subject_options_alter_subject_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_records', to='classes.subject'),
        ),
        migrations.AlterField(
            model_name='gradesummary',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_summary_records', to='classes.subject'),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
