# Generated by Django 4.1.13 on 2025-09-26 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='group_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='session_type',
            field=models.CharField(choices=[('lecture', 'Lý thuyết'), ('practice', 'Thực hành'), ('seminar', 'Seminar'), ('exam', 'Kiểm tra')], default='lecture', max_length=20),
        ),
    ]
