# Generated by Django 4.2.7 on 2025-09-24 00:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_id', models.CharField(max_length=20, unique=True, verbose_name='Mã khu')),
                ('building_name', models.CharField(max_length=100, verbose_name='Tên khu')),
                ('building_type', models.CharField(choices=[('academic', 'Học tập'), ('library', 'Thư viện'), ('it', 'Công nghệ thông tin'), ('admin', 'Hành chính'), ('lab', 'Phòng thí nghiệm')], default='academic', max_length=20, verbose_name='Loại khu')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Địa chỉ')),
                ('floors', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Số tầng')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Khu',
                'verbose_name_plural': 'Các khu',
                'db_table': 'buildings',
                'ordering': ['building_id'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=20, unique=True, verbose_name='Mã phòng')),
                ('room_name', models.CharField(max_length=100, verbose_name='Tên phòng')),
                ('floor', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Tầng')),
                ('room_type', models.CharField(choices=[('lecture', 'Phòng lý thuyết'), ('practice', 'Phòng thực hành'), ('lab', 'Phòng thí nghiệm'), ('hall', 'Hội trường'), ('library', 'Thư viện'), ('computer', 'Phòng máy tính'), ('meeting', 'Phòng họp'), ('office', 'Văn phòng')], default='lecture', max_length=20, verbose_name='Loại phòng')),
                ('capacity', models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Sức chứa')),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Diện tích (m²)')),
                ('equipment', models.TextField(blank=True, null=True, verbose_name='Thiết bị')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('status', models.CharField(choices=[('available', 'Trống'), ('occupied', 'Đang sử dụng'), ('maintenance', 'Bảo trì'), ('reserved', 'Đã đặt'), ('closed', 'Đóng cửa')], default='available', max_length=20, verbose_name='Trạng thái')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='rooms.building', verbose_name='Khu')),
            ],
            options={
                'verbose_name': 'Phòng học',
                'verbose_name_plural': 'Các phòng học',
                'db_table': 'rooms',
                'ordering': ['building', 'floor', 'room_id'],
                'unique_together': {('building', 'room_name')},
            },
        ),
        migrations.CreateModel(
            name='RoomSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('start_date', models.DateField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(verbose_name='Ngày kết thúc')),
                ('start_time', models.TimeField(verbose_name='Giờ bắt đầu')),
                ('end_time', models.TimeField(verbose_name='Giờ kết thúc')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='Lặp lại')),
                ('recurring_days', models.CharField(blank=True, max_length=20, null=True, verbose_name='Ngày lặp lại')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_schedules', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='rooms.room', verbose_name='Phòng')),
            ],
            options={
                'verbose_name': 'Lịch phòng',
                'verbose_name_plural': 'Lịch các phòng',
                'db_table': 'room_schedules',
                'ordering': ['start_date', 'start_time'],
            },
        ),
    ]
