# Generated by Django 4.2.7 on 2025-09-28 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0004_class_allow_auto_enroll_on_attendance_qr_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0002_attendancesession_group_name_and_more'),
        ('students', '0002_student_user_student_students_student_1ff8ed_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('assignment', 'Bài tập'), ('exam', 'Bài thi')], default='assignment', max_length=20)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='assignment_attachments/%Y/%m/')),
                ('release_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('time_limit_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('allowed_file_types', models.CharField(blank=True, help_text='vd: pdf,doc,docx,zip', max_length=200, null=True)),
                ('max_file_size_mb', models.PositiveIntegerField(default=20)),
                ('is_published', models.BooleanField(default=True)),
                ('points_max', models.DecimalField(decimal_places=2, default=10, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='classes.class')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assignments', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='attendance.attendancesession')),
            ],
            options={
                'db_table': 'assignments',
                'ordering': ['-release_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('personal_due_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='assignment_submissions/%Y/%m/')),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Đang làm'), ('submitted', 'Đã nộp'), ('late', 'Nộp trễ'), ('graded', 'Đã chấm'), ('auto_closed', 'Đã khóa')], default='draft', max_length=20)),
                ('is_late', models.BooleanField(default=False)),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assignments.assignment')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_submissions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to='students.student')),
            ],
            options={
                'db_table': 'assignment_submissions',
                'ordering': ['-uploaded_at', '-created_at'],
                'indexes': [models.Index(fields=['assignment'], name='assignment__assignm_df300a_idx'), models.Index(fields=['student'], name='assignment__student_f0cb4e_idx')],
                'unique_together': {('assignment', 'student', 'attempt_number')},
            },
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['class_obj'], name='assignments_class_o_8a27b0_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['type'], name='assignments_type_86bb18_idx'),
        ),
    ]
