# Generated by Django 4.2.7 on 2025-09-28 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0002_student_user_student_students_student_1ff8ed_idx_and_more'),
        ('classes', '0004_class_allow_auto_enroll_on_attendance_qr_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'groups',
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='GroupSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_size', models.PositiveIntegerField(default=3)),
                ('seed', models.CharField(blank=True, max_length=64, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_sets', to='classes.class')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_group_sets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'group_sets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='grouping.group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='students.student')),
            ],
            options={
                'db_table': 'group_members',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='groupset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='grouping.groupset'),
        ),
        migrations.AddIndex(
            model_name='groupset',
            index=models.Index(fields=['class_obj'], name='group_sets_class_o_626b7f_idx'),
        ),
        migrations.AddIndex(
            model_name='groupset',
            index=models.Index(fields=['created_at'], name='group_sets_created_837332_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmember',
            index=models.Index(fields=['group'], name='group_membe_group_i_d2cebc_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmember',
            index=models.Index(fields=['student'], name='group_membe_student_832526_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groupmember',
            unique_together={('group', 'student')},
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['groupset'], name='groups_groupse_0d5484_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('groupset', 'index')},
        ),
    ]
