# Generated by Django 4.1.13 on 2025-09-26 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0004_class_allow_auto_enroll_on_attendance_qr_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='class_materials/')),
                ('link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='classes.class')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_materials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'class_materials',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='classmaterial',
            index=models.Index(fields=['class_obj'], name='class_mater_class_o_757611_idx'),
        ),
        migrations.AddIndex(
            model_name='classmaterial',
            index=models.Index(fields=['created_at'], name='class_mater_created_3b2a72_idx'),
        ),
    ]
