# Generated by Django 4.2.7 on 2025-09-30 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0004_class_allow_auto_enroll_on_attendance_qr_and_more'),
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('lecture', 'Bài giảng'), ('syllabus', 'Đề cương'), ('exam', 'Đề thi'), ('assignment', 'Bài tập'), ('reference', 'Tài liệu tham khảo')], default='lecture', max_length=20)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=255, null=True)),
                ('allow_download', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('published', 'Đã công bố'), ('archived', 'Lưu trữ')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials_repository', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'materials',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_start_at', models.DateTimeField(blank=True, null=True)),
                ('publish_end_at', models.DateTimeField(blank=True, null=True)),
                ('allow_download', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_publications', to='classes.class')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='materials.material')),
            ],
            options={
                'db_table': 'material_publications',
            },
        ),
        migrations.AddField(
            model_name='material',
            name='published_classes',
            field=models.ManyToManyField(blank=True, related_name='published_materials', through='materials.MaterialPublication', to='classes.class'),
        ),
        migrations.CreateModel(
            name='MaterialVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='materials/')),
                ('version', models.PositiveIntegerField(default=1)),
                ('change_note', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_versions_created', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='materials.material')),
            ],
            options={
                'db_table': 'material_versions',
                'ordering': ['-version'],
                'indexes': [models.Index(fields=['material'], name='material_ve_materia_904894_idx'), models.Index(fields=['version'], name='material_ve_version_61c347_idx'), models.Index(fields=['created_at'], name='material_ve_created_4c5d28_idx')],
                'unique_together': {('material', 'version')},
            },
        ),
        migrations.AddIndex(
            model_name='materialpublication',
            index=models.Index(fields=['class_obj'], name='material_pu_class_o_f52cf6_idx'),
        ),
        migrations.AddIndex(
            model_name='materialpublication',
            index=models.Index(fields=['material'], name='material_pu_materia_b01452_idx'),
        ),
        migrations.AddIndex(
            model_name='materialpublication',
            index=models.Index(fields=['publish_start_at'], name='material_pu_publish_039a0f_idx'),
        ),
        migrations.AddIndex(
            model_name='materialpublication',
            index=models.Index(fields=['publish_end_at'], name='material_pu_publish_74a08c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='materialpublication',
            unique_together={('material', 'class_obj')},
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['type'], name='materials_type_6b994b_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['status'], name='materials_status_bf1b15_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['owner'], name='materials_owner_i_e33c04_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['created_at'], name='materials_created_65e81e_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['updated_at'], name='materials_updated_9233a4_idx'),
        ),
    ]
