# Generated by Django 4.2.7 on 2025-09-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_material_materialpublication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['is_deleted'], name='materials_is_dele_090a59_idx'),
        ),
    ]
