# Generated by Django 4.2.7 on 2025-09-20 13:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='teacher_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Mã giảng viên'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Số điện thoại không hợp lệ. Vd: 0123456789', regex='^(\\+84|84|0)?[0-9]{9,10}$')], verbose_name='Số điện thoại'),
        ),
    ]
