# Generated by Django 4.2.7 on 2025-09-24 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_teacher_id_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status_note',
            field=models.TextField(blank=True, null=True, verbose_name='Ghi chú trạng thái'),
        ),
    ]
