# Generated by Django 4.2.7 on 2025-09-28 05:03

import apps.submissions.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0004_class_allow_auto_enroll_on_attendance_qr_and_more'),
        ('students', '0002_student_user_student_students_student_1ff8ed_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to=apps.submissions.models.submission_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='classes.class')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_submissions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='students.student')),
            ],
            options={
                'db_table': 'submissions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['class_obj'], name='submissions_class_o_ef3059_idx'), models.Index(fields=['student'], name='submissions_student_51a963_idx'), models.Index(fields=['created_at'], name='submissions_created_ff86d7_idx')],
            },
        ),
    ]
