# Generated by Django 4.2.7 on 2025-09-24 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['class_id'], name='classes_class_i_c9f90e_idx'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['teacher'], name='classes_teacher_3b552b_idx'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['is_active'], name='classes_is_acti_7c0b49_idx'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['created_at'], name='classes_created_451968_idx'),
        ),
        migrations.AddIndex(
            model_name='classstudent',
            index=models.Index(fields=['class_obj'], name='class_stude_class_o_107c1d_idx'),
        ),
        migrations.AddIndex(
            model_name='classstudent',
            index=models.Index(fields=['student'], name='class_stude_student_a2eaf8_idx'),
        ),
        migrations.AddIndex(
            model_name='classstudent',
            index=models.Index(fields=['is_active'], name='class_stude_is_acti_f7b162_idx'),
        ),
        migrations.AddIndex(
            model_name='classstudent',
            index=models.Index(fields=['enrolled_at'], name='class_stude_enrolle_ca5188_idx'),
        ),
    ]
