# Generated by Django 4.1.13 on 2025-09-26 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_class_classes_class_i_c9f90e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_mode',
            field=models.CharField(choices=[('lecture_only', 'Lý thuyết'), ('practice_only', 'Thực hành'), ('lecture_practice', 'Lý thuyết + Thực hành')], default='lecture_only', max_length=32, verbose_name='Học phần'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['class_mode'], name='classes_class_m_c95507_idx'),
        ),
    ]
