# Generated by Django 4.2.7 on 2025-09-26 04:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0003_class_class_mode_class_classes_class_m_c95507_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='allow_auto_enroll_on_attendance_qr',
            field=models.BooleanField(default=True, help_text='Tự động ghi danh khi SV quét QR điểm danh nếu email hợp lệ'),
        ),
        migrations.AddField(
            model_name='class',
            name='restrict_to_roster_emails',
            field=models.BooleanField(default=False, help_text='Chỉ cho phép email có trong roster tham gia lớp'),
        ),
        migrations.AddField(
            model_name='classstudent',
            name='joined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classstudent',
            name='source',
            field=models.CharField(choices=[('import', 'Import'), ('join_code', 'Mã tham gia'), ('qr', 'Quét QR'), ('admin', 'Quản trị'), ('manual', 'Thủ công')], default='manual', max_length=16),
        ),
        migrations.AddField(
            model_name='classstudent',
            name='status',
            field=models.CharField(choices=[('invited', 'Được mời'), ('active', 'Đang tham gia'), ('removed', 'Đã rời lớp')], default='active', max_length=16),
        ),
        migrations.CreateModel(
            name='ClassJoinToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('max_uses', models.PositiveIntegerField(default=0, help_text='0 = unlimited')),
                ('use_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_tokens', to='classes.class')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_join_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'class_join_tokens',
                'indexes': [models.Index(fields=['token'], name='class_join__token_291c4e_idx'), models.Index(fields=['class_obj'], name='class_join__class_o_2bd524_idx'), models.Index(fields=['is_active'], name='class_join__is_acti_a27e3c_idx')],
            },
        ),
    ]
