# Generated by Django 4.2.7 on 2025-09-30 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0004_class_allow_auto_enroll_on_attendance_qr_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='AcademicYear',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('code', models.CharField(max_length=16, unique=True)),
                        ('name', models.CharField(max_length=32)),
                        ('start_date', models.DateField(blank=True, null=True)),
                        ('end_date', models.DateField(blank=True, null=True)),
                    ],
                    options={
                        'db_table': 'academic_years',
                        'ordering': ['-code'],
                    },
                )
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Subject',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('code', models.CharField(max_length=32, unique=True)),
                        ('name', models.CharField(max_length=128)),
                        ('credits', models.PositiveSmallIntegerField(default=3)),
                        ('description', models.TextField(blank=True, null=True)),
                    ],
                    options={
                        'db_table': 'subjects',
                        'ordering': ['code'],
                    },
                )
            ],
            database_operations=[],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('hk1', 'HK1'), ('hk2', 'HK2'), ('hk3', 'HK3')], max_length=8)),
                ('name', models.CharField(max_length=64)),
                ('is_current', models.BooleanField(default=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'terms',
            },
        ),
        # First wire FKs and fields, then create indexes depending on those fields
        migrations.AddField(
            model_name='term',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='classes.academicyear'),
        ),
        migrations.AddField(
            model_name='subject',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='class',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='classes.subject'),
        ),
        migrations.AddField(
            model_name='class',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='classes.term'),
        ),
        # Now safe to add indexes referencing new fields
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['teacher', 'term'], name='classes_teacher_3b62cd_idx'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['subject', 'term'], name='classes_subject_48920f_idx'),
        ),
        migrations.AddIndex(
            model_name='term',
            index=models.Index(fields=['year', 'season', 'is_current'], name='terms_year_id_be14af_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='term',
            unique_together={('year', 'season')},
        ),
    ]
