# Generated by Django 4.1.13 on 2025-10-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_academicyear_subject_term_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='is_current',
            field=models.BooleanField(default=False, help_text='Năm học hiện tại'),
        ),
    ]
