# Generated by Agent Mode to fix wrong FK on classes.subject_id (was pointing to grades_subjects)
from django.db import migrations


def fix_classes_subject_fk(apps, schema_editor):
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        # Drop wrong FK if exists
        try:
            cursor.execute("ALTER TABLE `classes` DROP FOREIGN KEY `classes_subject_id_020abeef_fk_subjects_id`;")
        except Exception:
            pass
        # Also drop any duplicated indexes on subject_id if necessary (ignore errors)
        try:
            cursor.execute("ALTER TABLE `classes` DROP INDEX `classes_subject_48920f_idx`;")
        except Exception:
            pass
        # Recreate proper index and FK to subjects(id)
        try:
            cursor.execute("ALTER TABLE `classes` ADD INDEX `classes_subject_48920f_idx` (`subject_id`, `term_id`);")
        except Exception:
            pass
        cursor.execute(
            "ALTER TABLE `classes` ADD CONSTRAINT `classes_subject_id_fk_subjects_id` FOREIGN KEY (`subject_id`) REFERENCES `subjects`(`id`) ON DELETE RESTRICT;"
        )


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('classes', '0007_create_subjects_table_if_missing'),
    ]

    operations = [
        migrations.RunPython(fix_classes_subject_fk, migrations.RunPython.noop),
    ]
